server:
  port: 9090

spring:
  application:
    name: eureka-client
  zipkin:
    enabled: true
    base-url: http://localhost:9411


eureka:
  instance:
    instance-id: eureka-client
    appname: ${spring.application.name}
    #prefer-ip-address: true
  client:
    # 指定是否注册到 Eureka
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:10097/eureka/
      # 如果Eureka是集群 则需要配置多台服务器
      # defaultZone: http://node1:10097/eureka/,http://node2:10098/eureka/

student:
  information:
    address: shanghai
    name: zhangsan

#Slueth
logging:
  level:
    root: trace
